const menuData = {
    mode: 'horizontal',
    // mode: 'vertical',
    sectionList: [{
        sectionIndex: 0,
        groupList: [{
            groupIndex: 0,
            title: '组0',
            blockList: [{
                col: 0,
                row: 0,
                width: 1,
                height: 1,
                title: '0-0'
            }, {
                col: 1,
                row: 0,
                width: 1,
                height: 1,
                title: '0-1'
            }, {
                col: 2,
                row: 0,
                width: 2,
                height: 2,
                title: '0-2'
            }, {
                col: 4,
                row: 0,
                width: 1,
                height: 1,
                title: '0-3'
            }, {
                col: 4,
                row: 1,
                width: 2,
                height: 2,
                title: '0-4'
            }, {
                col: 3,
                row: 3,
                width: 1,
                height: 1,
                title: '0-5'
            }, {
                col: 1,
                row: 3,
                width: 2,
                height: 2,
                title: '0-6'
            }, {
                col: 4,
                row: 5,
                width: 2,
                height: 2,
                title: '0-7'
            }, {
                col: 6,
                row: 0,
                width: 1,
                height: 1,
                title: '0-8'
            }, {
                col: 7,
                row: 0,
                width: 2,
                height: 2,
                title: '0-9'
            }, {
                col: 10,
                row: 0,
                width: 1,
                height: 1,
                title: '0-10'
            }, {
                col: 8,
                row: 2,
                width: 2,
                height: 2,
                title: '0-11'
            }]
        }, {
            groupIndex: 1,
            title: '组1',
            blockList: [{
                col: 0,
                row: 0,
                width: 2,
                height: 2,
                title: '1-0'
            }, {
                col: 3,
                row: 1,
                width: 1,
                height: 1,
                title: '1-1'
            }, {
                col: 4,
                row: 0,
                width: 2,
                height: 2,
                title: '1-2'
            }, {
                col: 0,
                row: 2,
                width: 2,
                height: 2,
                title: '1-3'
            }, {
                col: 2,
                row: 2,
                width: 1,
                height: 1,
                title: '1-4'
            }, {
                col: 2,
                row: 3,
                width: 1,
                height: 1,
                title: '1-5'
            }, {
                col: 3,
                row: 2,
                width: 2,
                height: 2,
                title: '1-6'
            }, {
                col: 0,
                row: 4,
                width: 4,
                height: 2,
                title: '1-7'
            }, {
                col: 4,
                row: 4,
                width: 1,
                height: 1,
                title: '1-8'
            }]
        }, {
            groupIndex: 2,
            title: '组2',
            blockList: [{
                col: 0,
                row: 0,
                width: 4,
                height: 4,
                title: '2-0'
            }, {
                col: 4,
                row: 1,
                width: 1,
                height: 1,
                title: '2-1'
            }, {
                col: 0,
                row: 4,
                width: 1,
                height: 1,
                title: '2-2'
            }, {
                col: 1,
                row: 4,
                width: 2,
                height: 2,
                title: '2-3'
            }, {
                col: 3,
                row: 5,
                width: 1,
                height: 1,
                title: '2-4'
            }, {
                col: 4,
                row: 3,
                width: 2,
                height: 2,
                title: '2-4'
            }]
        }]
    }, {
        sectionIndex: 1,
        groupList: [{
            groupIndex: 0,
            title: '组0',
            blockList: [{
                col: 0,
                row: 0,
                width: 1,
                height: 1,
                title: '0-0'
            }, {
                col: 1,
                row: 0,
                width: 1,
                height: 1,
                title: '0-1'
            }, {
                col: 2,
                row: 0,
                width: 2,
                height: 2,
                title: '0-2'
            }, {
                col: 4,
                row: 0,
                width: 1,
                height: 1,
                title: '0-3'
            }, {
                col: 4,
                row: 1,
                width: 2,
                height: 2,
                title: '0-4'
            }, {
                col: 3,
                row: 3,
                width: 1,
                height: 1,
                title: '0-5'
            }, {
                col: 1,
                row: 3,
                width: 2,
                height: 2,
                title: '0-6'
            }, {
                col: 4,
                row: 5,
                width: 2,
                height: 2,
                title: '0-7'
            }, {
                col: 6,
                row: 0,
                width: 1,
                height: 1,
                title: '0-8'
            }, {
                col: 7,
                row: 0,
                width: 2,
                height: 2,
                title: '0-9'
            }, {
                col: 10,
                row: 0,
                width: 1,
                height: 1,
                title: '0-10'
            }, {
                col: 8,
                row: 2,
                width: 2,
                height: 2,
                title: '0-11'
            }]
        }, {
            groupIndex: 1,
            title: '组1',
            blockList: [{
                col: 0,
                row: 0,
                width: 2,
                height: 2,
                title: '1-0'
            }, {
                col: 3,
                row: 1,
                width: 1,
                height: 1,
                title: '1-1'
            }, {
                col: 4,
                row: 0,
                width: 2,
                height: 2,
                title: '1-2'
            }, {
                col: 0,
                row: 2,
                width: 2,
                height: 2,
                title: '1-3'
            }, {
                col: 2,
                row: 2,
                width: 1,
                height: 1,
                title: '1-4'
            }, {
                col: 2,
                row: 3,
                width: 1,
                height: 1,
                title: '1-5'
            }, {
                col: 3,
                row: 2,
                width: 2,
                height: 2,
                title: '1-6'
            }, {
                col: 0,
                row: 4,
                width: 4,
                height: 2,
                title: '1-7'
            }, {
                col: 4,
                row: 4,
                width: 1,
                height: 1,
                title: '1-8'
            }]
        }, {
            groupIndex: 2,
            title: '组2',
            blockList: [{
                col: 0,
                row: 0,
                width: 4,
                height: 4,
                title: '2-0'
            }, {
                col: 4,
                row: 1,
                width: 1,
                height: 1,
                title: '2-1'
            }, {
                col: 0,
                row: 4,
                width: 1,
                height: 1,
                title: '2-2'
            }, {
                col: 1,
                row: 4,
                width: 2,
                height: 2,
                title: '2-3'
            }, {
                col: 3,
                row: 5,
                width: 1,
                height: 1,
                title: '2-4'
            }, {
                col: 4,
                row: 3,
                width: 2,
                height: 2,
                title: '2-4'
            }]
        }]
    }]
}
export default menuData
